# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kotlin.es
email: your-email@domain.com
description: La primera comunidad de Kotlin en espa√±ol
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kotlin.es" # the base hostname & protocol for your site
twitter_username: kotlin-es
github_username:  kotlin-es
facebook_username: kotlin.es
last_kotlin_version: 1.0.3

# Build settings
markdown: kramdown

gems:
#- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed

permalink: /:year/:month/:title/

paginate: 6
paginate_path: "/page/:num/"

# sudo gem install jekyll-mentions jemoji jekyll-redirect-from jekyll-sitemap jekyll-feed

